/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSystemRouteRouteImport } from './routes/admin/system/route'
import { Route as AdminReviewsRouteRouteImport } from './routes/admin/reviews/route'
import { Route as AdminContentRouteRouteImport } from './routes/admin/content/route'
import { Route as AdminSystemIndexRouteImport } from './routes/admin/system/index'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin/reviews/index'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content/index'
import { Route as AdminReviewsArticlesRouteRouteImport } from './routes/admin/reviews/articles/route'
import { Route as AdminContentArticlesRouteRouteImport } from './routes/admin/content/articles/route'
import { Route as AdminSystemUsersIndexRouteImport } from './routes/admin/system/users/index'
import { Route as AdminSystemRolesIndexRouteImport } from './routes/admin/system/roles/index'
import { Route as AdminSystemAccessesIndexRouteImport } from './routes/admin/system/accesses/index'
import { Route as AdminReviewsArticlesIndexRouteImport } from './routes/admin/reviews/articles/index'
import { Route as AdminContentTagsIndexRouteImport } from './routes/admin/content/tags/index'
import { Route as AdminContentCategoriesIndexRouteImport } from './routes/admin/content/categories/index'
import { Route as AdminContentArticlesIndexRouteImport } from './routes/admin/content/articles/index'
import { Route as AdminContentArticlesNewRouteImport } from './routes/admin/content/articles/new'
import { Route as AdminContentArticlesIdRouteRouteImport } from './routes/admin/content/articles/$id/route'
import { Route as AdminReviewsArticlesIdIndexRouteImport } from './routes/admin/reviews/articles/$id/index'
import { Route as AdminContentArticlesIdIndexRouteImport } from './routes/admin/content/articles/$id/index'
import { Route as AdminContentArticlesIdEditRouteImport } from './routes/admin/content/articles/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemRouteRoute = AdminSystemRouteRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRouteRoute = AdminReviewsRouteRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRouteRoute = AdminContentRouteRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemIndexRoute = AdminSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminReviewsRouteRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContentRouteRoute,
} as any)
const AdminReviewsArticlesRouteRoute =
  AdminReviewsArticlesRouteRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AdminReviewsRouteRoute,
  } as any)
const AdminContentArticlesRouteRoute =
  AdminContentArticlesRouteRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AdminContentRouteRoute,
  } as any)
const AdminSystemUsersIndexRoute = AdminSystemUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminSystemRolesIndexRoute = AdminSystemRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminSystemAccessesIndexRoute =
  AdminSystemAccessesIndexRouteImport.update({
    id: '/accesses/',
    path: '/accesses/',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminReviewsArticlesIndexRoute =
  AdminReviewsArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminReviewsArticlesRouteRoute,
  } as any)
const AdminContentTagsIndexRoute = AdminContentTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminContentRouteRoute,
} as any)
const AdminContentCategoriesIndexRoute =
  AdminContentCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AdminContentRouteRoute,
  } as any)
const AdminContentArticlesIndexRoute =
  AdminContentArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminContentArticlesRouteRoute,
  } as any)
const AdminContentArticlesNewRoute = AdminContentArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContentArticlesRouteRoute,
} as any)
const AdminContentArticlesIdRouteRoute =
  AdminContentArticlesIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminContentArticlesRouteRoute,
  } as any)
const AdminReviewsArticlesIdIndexRoute =
  AdminReviewsArticlesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AdminReviewsArticlesRouteRoute,
  } as any)
const AdminContentArticlesIdIndexRoute =
  AdminContentArticlesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminContentArticlesIdRouteRoute,
  } as any)
const AdminContentArticlesIdEditRoute =
  AdminContentArticlesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminContentArticlesIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/content': typeof AdminContentRouteRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRouteRouteWithChildren
  '/admin/system': typeof AdminSystemRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/content/articles': typeof AdminContentArticlesRouteRouteWithChildren
  '/admin/reviews/articles': typeof AdminReviewsArticlesRouteRouteWithChildren
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/admin/content/articles/$id': typeof AdminContentArticlesIdRouteRouteWithChildren
  '/admin/content/articles/new': typeof AdminContentArticlesNewRoute
  '/admin/content/articles/': typeof AdminContentArticlesIndexRoute
  '/admin/content/categories/': typeof AdminContentCategoriesIndexRoute
  '/admin/content/tags/': typeof AdminContentTagsIndexRoute
  '/admin/reviews/articles/': typeof AdminReviewsArticlesIndexRoute
  '/admin/system/accesses/': typeof AdminSystemAccessesIndexRoute
  '/admin/system/roles/': typeof AdminSystemRolesIndexRoute
  '/admin/system/users/': typeof AdminSystemUsersIndexRoute
  '/admin/content/articles/$id/edit': typeof AdminContentArticlesIdEditRoute
  '/admin/content/articles/$id/': typeof AdminContentArticlesIdIndexRoute
  '/admin/reviews/articles/$id/': typeof AdminReviewsArticlesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/system': typeof AdminSystemIndexRoute
  '/admin/content/articles/new': typeof AdminContentArticlesNewRoute
  '/admin/content/articles': typeof AdminContentArticlesIndexRoute
  '/admin/content/categories': typeof AdminContentCategoriesIndexRoute
  '/admin/content/tags': typeof AdminContentTagsIndexRoute
  '/admin/reviews/articles': typeof AdminReviewsArticlesIndexRoute
  '/admin/system/accesses': typeof AdminSystemAccessesIndexRoute
  '/admin/system/roles': typeof AdminSystemRolesIndexRoute
  '/admin/system/users': typeof AdminSystemUsersIndexRoute
  '/admin/content/articles/$id/edit': typeof AdminContentArticlesIdEditRoute
  '/admin/content/articles/$id': typeof AdminContentArticlesIdIndexRoute
  '/admin/reviews/articles/$id': typeof AdminReviewsArticlesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/content': typeof AdminContentRouteRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRouteRouteWithChildren
  '/admin/system': typeof AdminSystemRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/content/articles': typeof AdminContentArticlesRouteRouteWithChildren
  '/admin/reviews/articles': typeof AdminReviewsArticlesRouteRouteWithChildren
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/admin/content/articles/$id': typeof AdminContentArticlesIdRouteRouteWithChildren
  '/admin/content/articles/new': typeof AdminContentArticlesNewRoute
  '/admin/content/articles/': typeof AdminContentArticlesIndexRoute
  '/admin/content/categories/': typeof AdminContentCategoriesIndexRoute
  '/admin/content/tags/': typeof AdminContentTagsIndexRoute
  '/admin/reviews/articles/': typeof AdminReviewsArticlesIndexRoute
  '/admin/system/accesses/': typeof AdminSystemAccessesIndexRoute
  '/admin/system/roles/': typeof AdminSystemRolesIndexRoute
  '/admin/system/users/': typeof AdminSystemUsersIndexRoute
  '/admin/content/articles/$id/edit': typeof AdminContentArticlesIdEditRoute
  '/admin/content/articles/$id/': typeof AdminContentArticlesIdIndexRoute
  '/admin/reviews/articles/$id/': typeof AdminReviewsArticlesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/content'
    | '/admin/reviews'
    | '/admin/system'
    | '/admin/'
    | '/admin/content/articles'
    | '/admin/reviews/articles'
    | '/admin/content/'
    | '/admin/reviews/'
    | '/admin/system/'
    | '/admin/content/articles/$id'
    | '/admin/content/articles/new'
    | '/admin/content/articles/'
    | '/admin/content/categories/'
    | '/admin/content/tags/'
    | '/admin/reviews/articles/'
    | '/admin/system/accesses/'
    | '/admin/system/roles/'
    | '/admin/system/users/'
    | '/admin/content/articles/$id/edit'
    | '/admin/content/articles/$id/'
    | '/admin/reviews/articles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/content'
    | '/admin/reviews'
    | '/admin/system'
    | '/admin/content/articles/new'
    | '/admin/content/articles'
    | '/admin/content/categories'
    | '/admin/content/tags'
    | '/admin/reviews/articles'
    | '/admin/system/accesses'
    | '/admin/system/roles'
    | '/admin/system/users'
    | '/admin/content/articles/$id/edit'
    | '/admin/content/articles/$id'
    | '/admin/reviews/articles/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/content'
    | '/admin/reviews'
    | '/admin/system'
    | '/admin/'
    | '/admin/content/articles'
    | '/admin/reviews/articles'
    | '/admin/content/'
    | '/admin/reviews/'
    | '/admin/system/'
    | '/admin/content/articles/$id'
    | '/admin/content/articles/new'
    | '/admin/content/articles/'
    | '/admin/content/categories/'
    | '/admin/content/tags/'
    | '/admin/reviews/articles/'
    | '/admin/system/accesses/'
    | '/admin/system/roles/'
    | '/admin/system/users/'
    | '/admin/content/articles/$id/edit'
    | '/admin/content/articles/$id/'
    | '/admin/reviews/articles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system/': {
      id: '/admin/system/'
      path: '/'
      fullPath: '/admin/system/'
      preLoaderRoute: typeof AdminSystemIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminReviewsRouteRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/admin/reviews/articles': {
      id: '/admin/reviews/articles'
      path: '/articles'
      fullPath: '/admin/reviews/articles'
      preLoaderRoute: typeof AdminReviewsArticlesRouteRouteImport
      parentRoute: typeof AdminReviewsRouteRoute
    }
    '/admin/content/articles': {
      id: '/admin/content/articles'
      path: '/articles'
      fullPath: '/admin/content/articles'
      preLoaderRoute: typeof AdminContentArticlesRouteRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/admin/system/users/': {
      id: '/admin/system/users/'
      path: '/users'
      fullPath: '/admin/system/users/'
      preLoaderRoute: typeof AdminSystemUsersIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/roles/': {
      id: '/admin/system/roles/'
      path: '/roles'
      fullPath: '/admin/system/roles/'
      preLoaderRoute: typeof AdminSystemRolesIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/accesses/': {
      id: '/admin/system/accesses/'
      path: '/accesses'
      fullPath: '/admin/system/accesses/'
      preLoaderRoute: typeof AdminSystemAccessesIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/reviews/articles/': {
      id: '/admin/reviews/articles/'
      path: '/'
      fullPath: '/admin/reviews/articles/'
      preLoaderRoute: typeof AdminReviewsArticlesIndexRouteImport
      parentRoute: typeof AdminReviewsArticlesRouteRoute
    }
    '/admin/content/tags/': {
      id: '/admin/content/tags/'
      path: '/tags'
      fullPath: '/admin/content/tags/'
      preLoaderRoute: typeof AdminContentTagsIndexRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/admin/content/categories/': {
      id: '/admin/content/categories/'
      path: '/categories'
      fullPath: '/admin/content/categories/'
      preLoaderRoute: typeof AdminContentCategoriesIndexRouteImport
      parentRoute: typeof AdminContentRouteRoute
    }
    '/admin/content/articles/': {
      id: '/admin/content/articles/'
      path: '/'
      fullPath: '/admin/content/articles/'
      preLoaderRoute: typeof AdminContentArticlesIndexRouteImport
      parentRoute: typeof AdminContentArticlesRouteRoute
    }
    '/admin/content/articles/new': {
      id: '/admin/content/articles/new'
      path: '/new'
      fullPath: '/admin/content/articles/new'
      preLoaderRoute: typeof AdminContentArticlesNewRouteImport
      parentRoute: typeof AdminContentArticlesRouteRoute
    }
    '/admin/content/articles/$id': {
      id: '/admin/content/articles/$id'
      path: '/$id'
      fullPath: '/admin/content/articles/$id'
      preLoaderRoute: typeof AdminContentArticlesIdRouteRouteImport
      parentRoute: typeof AdminContentArticlesRouteRoute
    }
    '/admin/reviews/articles/$id/': {
      id: '/admin/reviews/articles/$id/'
      path: '/$id'
      fullPath: '/admin/reviews/articles/$id/'
      preLoaderRoute: typeof AdminReviewsArticlesIdIndexRouteImport
      parentRoute: typeof AdminReviewsArticlesRouteRoute
    }
    '/admin/content/articles/$id/': {
      id: '/admin/content/articles/$id/'
      path: '/'
      fullPath: '/admin/content/articles/$id/'
      preLoaderRoute: typeof AdminContentArticlesIdIndexRouteImport
      parentRoute: typeof AdminContentArticlesIdRouteRoute
    }
    '/admin/content/articles/$id/edit': {
      id: '/admin/content/articles/$id/edit'
      path: '/edit'
      fullPath: '/admin/content/articles/$id/edit'
      preLoaderRoute: typeof AdminContentArticlesIdEditRouteImport
      parentRoute: typeof AdminContentArticlesIdRouteRoute
    }
  }
}

interface AdminContentArticlesIdRouteRouteChildren {
  AdminContentArticlesIdEditRoute: typeof AdminContentArticlesIdEditRoute
  AdminContentArticlesIdIndexRoute: typeof AdminContentArticlesIdIndexRoute
}

const AdminContentArticlesIdRouteRouteChildren: AdminContentArticlesIdRouteRouteChildren =
  {
    AdminContentArticlesIdEditRoute: AdminContentArticlesIdEditRoute,
    AdminContentArticlesIdIndexRoute: AdminContentArticlesIdIndexRoute,
  }

const AdminContentArticlesIdRouteRouteWithChildren =
  AdminContentArticlesIdRouteRoute._addFileChildren(
    AdminContentArticlesIdRouteRouteChildren,
  )

interface AdminContentArticlesRouteRouteChildren {
  AdminContentArticlesIdRouteRoute: typeof AdminContentArticlesIdRouteRouteWithChildren
  AdminContentArticlesNewRoute: typeof AdminContentArticlesNewRoute
  AdminContentArticlesIndexRoute: typeof AdminContentArticlesIndexRoute
}

const AdminContentArticlesRouteRouteChildren: AdminContentArticlesRouteRouteChildren =
  {
    AdminContentArticlesIdRouteRoute:
      AdminContentArticlesIdRouteRouteWithChildren,
    AdminContentArticlesNewRoute: AdminContentArticlesNewRoute,
    AdminContentArticlesIndexRoute: AdminContentArticlesIndexRoute,
  }

const AdminContentArticlesRouteRouteWithChildren =
  AdminContentArticlesRouteRoute._addFileChildren(
    AdminContentArticlesRouteRouteChildren,
  )

interface AdminContentRouteRouteChildren {
  AdminContentArticlesRouteRoute: typeof AdminContentArticlesRouteRouteWithChildren
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminContentCategoriesIndexRoute: typeof AdminContentCategoriesIndexRoute
  AdminContentTagsIndexRoute: typeof AdminContentTagsIndexRoute
}

const AdminContentRouteRouteChildren: AdminContentRouteRouteChildren = {
  AdminContentArticlesRouteRoute: AdminContentArticlesRouteRouteWithChildren,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminContentCategoriesIndexRoute: AdminContentCategoriesIndexRoute,
  AdminContentTagsIndexRoute: AdminContentTagsIndexRoute,
}

const AdminContentRouteRouteWithChildren =
  AdminContentRouteRoute._addFileChildren(AdminContentRouteRouteChildren)

interface AdminReviewsArticlesRouteRouteChildren {
  AdminReviewsArticlesIndexRoute: typeof AdminReviewsArticlesIndexRoute
  AdminReviewsArticlesIdIndexRoute: typeof AdminReviewsArticlesIdIndexRoute
}

const AdminReviewsArticlesRouteRouteChildren: AdminReviewsArticlesRouteRouteChildren =
  {
    AdminReviewsArticlesIndexRoute: AdminReviewsArticlesIndexRoute,
    AdminReviewsArticlesIdIndexRoute: AdminReviewsArticlesIdIndexRoute,
  }

const AdminReviewsArticlesRouteRouteWithChildren =
  AdminReviewsArticlesRouteRoute._addFileChildren(
    AdminReviewsArticlesRouteRouteChildren,
  )

interface AdminReviewsRouteRouteChildren {
  AdminReviewsArticlesRouteRoute: typeof AdminReviewsArticlesRouteRouteWithChildren
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
}

const AdminReviewsRouteRouteChildren: AdminReviewsRouteRouteChildren = {
  AdminReviewsArticlesRouteRoute: AdminReviewsArticlesRouteRouteWithChildren,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
}

const AdminReviewsRouteRouteWithChildren =
  AdminReviewsRouteRoute._addFileChildren(AdminReviewsRouteRouteChildren)

interface AdminSystemRouteRouteChildren {
  AdminSystemIndexRoute: typeof AdminSystemIndexRoute
  AdminSystemAccessesIndexRoute: typeof AdminSystemAccessesIndexRoute
  AdminSystemRolesIndexRoute: typeof AdminSystemRolesIndexRoute
  AdminSystemUsersIndexRoute: typeof AdminSystemUsersIndexRoute
}

const AdminSystemRouteRouteChildren: AdminSystemRouteRouteChildren = {
  AdminSystemIndexRoute: AdminSystemIndexRoute,
  AdminSystemAccessesIndexRoute: AdminSystemAccessesIndexRoute,
  AdminSystemRolesIndexRoute: AdminSystemRolesIndexRoute,
  AdminSystemUsersIndexRoute: AdminSystemUsersIndexRoute,
}

const AdminSystemRouteRouteWithChildren =
  AdminSystemRouteRoute._addFileChildren(AdminSystemRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminContentRouteRoute: typeof AdminContentRouteRouteWithChildren
  AdminReviewsRouteRoute: typeof AdminReviewsRouteRouteWithChildren
  AdminSystemRouteRoute: typeof AdminSystemRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContentRouteRoute: AdminContentRouteRouteWithChildren,
  AdminReviewsRouteRoute: AdminReviewsRouteRouteWithChildren,
  AdminSystemRouteRoute: AdminSystemRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
